"""
magnafpm
RotorDiskRadius Rout
RotorDiskInnerRadius Rin
DiskThickness hr
MagnetLength la
MagnetWidth wm
MagnetThickness hm
MagnetMaterial ?
NumberMagnet magnet_num
StatorThickness tw
CoilType coil_type
CoilLegWidth wc
CoilInnerWidth1 coil_hole_Rout_constr
CoilInnerWidth2 coil_hole_Rin_constr
MechanicalClearance g
InnerDistanceBetweenMagnets dist_magnet_Rin
NumberOfCoilsPerPhase q

furling
VerticalPlaneAngle
HorizontalPlaneAngle
BracketLength
BracketWidth
BracketThickness
BoomLength
BoomPipeDiameter
BoomPipeThickness
VaneThickness
VaneLength
VaneWidth
Offset

user
HubPitchCircleDiameter
RotorDiskCentralHoleDiameter
HolesDiameter
MetalLengthL
MetalThicknessL
FlatMetalThickness
YawPipeDiameter
PipeThickness
RotorResinMargin
HubHolesDiameter
"""